### ISSUE TITLE
方法名的命名方式是不是可以改为统一模式？

### ISSUE THREAD

**Issue by SherlockLiang** [bokire/fastdfs-spring-boot-starter#1]

**Comment by bokire** [comment]
麻烦你描述的再详细点，举个例子

**Comment by SherlockLiang** [comment]
您好！例如像FastDfsTemplate 。有的方法名是borrowTrackerServer()这样驼峰命名法，但是另外也存在upload_file()这样的下划线命名法。由于本人有点强迫症，只是建议一下统一。谢谢！

**Comment by bokire** [comment]
哈哈，，fastdfs-client-jar里面就是这样命名的，我自己偷懒了，不想改以前的代码了，所以这部分没改
